services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "refweaver.api.main"]
    environment:
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:?err}
      OPENAI_API_KEY: ${OPENAI_API_KEY:?err}
      DATABASE_URL: postgres://refweaver:${DB_PASSWORD:?err}@postgres:5432/refweaver
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  postgres:
    image: docker.io/library/postgres:16-alpine
    environment:
      POSTGRES_USER: refweaver
      POSTGRES_DB: refweaver
      POSTGRES_PASSWORD: ${DB_PASSWORD:?err}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U refweaver -d refweaver"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: docker.io/redis/redis-stack:7.2.0-v9
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
