"""init

Revision ID: ab1d2e193ba4
Revises: 
Create Date: 2026-02-27 20:55:52.945280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1d2e193ba4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('doi', sa.String(length=128), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_user_id'), 'runs', ['user_id'], unique=False)
    op.create_table('sentences',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sentence_with_context', sa.Text(), nullable=True),
    sa.Column('rewrite_applied', sa.Boolean(), nullable=False),
    sa.Column('needs_reference', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentences_run_id'), 'sentences', ['run_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sentence_id', sa.String(length=64), nullable=False),
    sa.Column('article_id', sa.String(length=64), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('relevance_reasoning', sa.Text(), nullable=True),
    sa.Column('is_relevant', sa.Boolean(), nullable=False),
    sa.Column('stance', sa.String(length=32), nullable=True),
    sa.Column('stance_confidence', sa.Float(), nullable=True),
    sa.Column('stance_reasoning', sa.Text(), nullable=True),
    sa.Column('supporting_evidence', sa.Text(), nullable=True),
    sa.Column('suggested_modification', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_article_id'), 'evaluations', ['article_id'], unique=False)
    op.create_index(op.f('ix_evaluations_sentence_id'), 'evaluations', ['sentence_id'], unique=False)
    op.create_table('verdicts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sentence_id', sa.String(length=64), nullable=False),
    sa.Column('overall_assessment', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('primary_sources', sa.JSON(), nullable=False),
    sa.Column('primary_source_identifiers', sa.JSON(), nullable=False),
    sa.Column('synthesis', sa.Text(), nullable=False),
    sa.Column('suggested_citation', sa.Text(), nullable=True),
    sa.Column('suggested_rewording', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sentence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verdicts')
    op.drop_index(op.f('ix_evaluations_sentence_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_article_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_sentences_run_id'), table_name='sentences')
    op.drop_table('sentences')
    op.drop_index(op.f('ix_runs_user_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_table('users')
    op.drop_table('articles')
    # ### end Alembic commands ###
